name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t xiaosi-maritime-single-window .
          docker tag xiaosi-maritime-single-window xiaosihuangsi/xiaosi-maritime-single-window
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u xiaosihuangsi --password-stdin
          docker push xiaosihuangsi/xiaosi-maritime-single-window

      # Add more steps here for testing, linting, etc.
