name: Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Decode SSH Key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" | base64 --decode > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> $HOME/.ssh/known_hosts

      - name: Deploy to EC2 instance
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
            sudo docker run -d --restart unless-stopped --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
          '

